config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :people do
    collection do
      get :roomid
    end
  end
  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    def index
        @people = Person.all
    end

    def show
        @person = Person.find(params[:id])
    end

    def new
        @person = Person.new
    end

    def create
        @person = Person.new(person_params)

        if params[:next_step]
            redirect_to roomid_people_path
        
        elsif @person.save
            redirect_to @person

        else
            render 'new'
        end
    end

    def edit
        @person = Person.find(params[:id])
    end

    def update
        @person = Person.find(params[:id])

        if @person.update(person_params)
            redirect_to @person
        else
            render 'edit'
        end
    end

    def destroy
        @person = Person.find(params[:id])
        @person.destroy
        
        redirect_to people_path
    end
private
    def person_params
        params.require(:person).permit(:customer, :date, :jobsite, :attn, :phone, :email, :next_step, :gender, :choice)
    end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
def index
    @rooms = Room.all()
end

def show
    @room= Room.find(params[:id])
end

def new
    @room = Room.new
end

def create
    @room = Room.new(room_params)
end

private
    def room_params
        params.require(:room).permit(:customer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<%= link_to 'Customers', controller: 'people' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contract Software - Uncle Kam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: @person, local: true) do |form| %>
    <% if  @person.errors.any? %>
        <div id = "error_explanation">
            <h2>
                <%= pluralize(@person.errors.count, "error") %> prohibits you from continuing:
            </h2>
            <ul>
                <% @person.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
    <%= form.label :customer, "Customer" %><br>
    <%= form.text_field :customer %>
</p>

    <p>
        <%= form.label :date, "Date" %><br>
        <%= form.text_field :date %>
    </p>

    <p>
        <%= form.label :jobsite, "Job Site" %><br>
        <%= form.text_field :jobsite %>
    </p>

    <p>
        <%= form.label :attn, "ATTN" %><br>
        <%= form.text_field :attn %>
    </p>  
    
    <p>
        <%= form.label :phone, "Tel" %><br>
        <%= form.text_field :phone %>
    </p>       
    
    <p>
        <%= form.label :email, "email" %><br>
        <%= form.text_field :email %>
    </p>
        
    <p>
        <%= submit_tag("Submit") %>
    </p>
<% end %>

<%= link_to 'Back', people_path %>

app/views/people/edit.html.erb
<h1>Edit Personal Information</h1>
 
<%= form_with(model: @person, local: true) do |form| %>
    <p>
        <%= form.label :customer, "Customer" %><br>
        <%= form.text_field :customer %>
    </p>

    <p>
        <%= form.label :date, "Date" %><br>
        <%= form.text_field :date %>
    </p>

    <p>
        <%= form.label :jobsite, "Job Site" %><br>
        <%= form.text_field :jobsite %>
    </p>

    <p>
        <%= form.label :attn, "ATTN" %><br>
        <%= form.text_field :attn %>
    </p>

    <p>
        <%= form.label :phone, "Tel" %><br>
        <%= form.text_field :phone %>
    </p>

    <p>
        <%= form.label :email, "Email" %><br>
        <%= form.text_field :email %>
    </p>

    <p>
        <%= submit_tag("Re-Submit") %>
    </p>
<% end %>

<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Current Customers</h1>
 

<%= link_to 'New Customer', new_person_path %>

<table>
  <tr>
    <th>Customer</th>
    <th>Date</th>
    <th>Job Site </th>
    <th>Attn </th>
    <th>Tel</th>
    <th>Email</th>
    <th>
    <th colspan="2"></th>
  </tr>
 
  <% @people.each do |person| %>
    <tr>
      <td><%= person.customer %></td>
      <td><%= person.date %></td>
      <td><%= person.jobsite %></td>
      <td><%= person.attn %></td>
      <td><%= person.phone %></td>
      <td><%= person.email %></td>
      <td><%= link_to 'Show', person_path(person) %></td>
      <td><%= link_to 'Edit', edit_person_path(person) %></td>
      <td><%= link_to 'Delete', person_path(person), method: :delete, data:{confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', home_index_path %>

app/views/people/new.html.erb
<h1> New Customer - Personal Information </h1>

<%= form_with scope: :person , url: people_path, local: true do |form| %>
    <% if  @person.errors.any? %>
        <div id = "error_explanation">
            <h2>
                <%= pluralize(@person.errors.count, "error") %> prohibits you from continuing:
            </h2>
            <ul>
                <% @person.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        
    <% end %>

    <p>
        <%= form.label :customer, "Customer" %><br>
        <%= form.text_field :customer %>
    </p>

    <p>
        <%= form.label :date, "Date" %><br>
        <%= form.text_field :date %>
    </p>
    
    <p>
        <%= form.label :jobsite, "Job Site" %><br>
        <%= form.text_field :jobsite %>
    </p>

    <p>
        <%= form.label :attn, "ATTN" %><br>
        <%= form.text_field :attn %>
    </p>

    <p>
        <%= form.label :phone, "Tel" %><br>
        <%= form.text_field :phone %>
    </p>
    
    <p>
        <%= form.label :email, "Email" %><br>
        <%= form.text_field :email %>
    </p>

    <p>
        <%= form.submit "Next Step", :name => "next_step" %>
    </p>

    <p>
        <%= submit_tag "Save" %>
    </p>

<% end %>


<%= link_to 'Back', people_path %>

app/views/people/roomid.html.erb
<h1> Room </h1>

<%= form_with scope: :roomid , url: roomid_people_path, local: true do |form| %>
    <p>
        <b><%= form.label :gender, "Location" %></b>
        <%= form.select(:gender, [ 'Male', 'Female' ], {}, { :class => 'select' }) %>
    </p>

    <p>
        <b> Does this location have an ID ?</b><br />
        <fieldset>
        <%= form.radio_button :choice, 'Yes' %> Yes <br />
        <%= form.radio_button :choice, 'No' %> No <br />
        </fieldset>
    </p>

    
<% end %>

app/views/people/show.html.erb
<p>
    <strong> Customer: </strong>
    <%= @person.customer %>
</p>

<p>
    <strong> Date: </strong>
    <%= @person.date %>
</p>

<p>
    <strong> Job Site: </strong>
    <%= @person.jobsite %>
</p>

<p>
    <strong> Attn: </strong>
    <%= @person.attn %>
</p>

<p>
    <strong> Tel: </strong>
    <%= @person.phone %>
</p>

<p>
    <strong> Email: </strong>
    <%= @person.email %>
</p>


<%= link_to 'Back', people_path %>